name: Deploy react app
on:
  push:
    branches:
      -  master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build docker image
        run: |
             docker build -t nkathad/docker-react -f Dockerfile.dev .
      - name:   Run test
        run: docker run nkathad/docker-react npm run test -- --coverage  

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Elastic Beanstalk CLI
        run: |
          wget https://s3.amazonaws.com/elasticbeanstalk-cli-resources/cli/AWS-ElasticBeanstalk-CLI-2.2.2.zip
          unzip AWS-ElasticBeanstalk-CLI-2.2.2.zip
          sudo mv AWS-ElasticBeanstalk-CLI-2.2.2/ /opt/
          sudo ln -s /opt/AWS-ElasticBeanstalk-CLI-2.2.2/eb /usr/local/bin/eb
      - name: Deploy to elastinbeanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to Elastic Beanstalk
        run: eb deploy  Docker-react-env   
     
        
 
