name: build and deploy on EBS
on:
  push:
    branches:
      -  master 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: build docker image
        run: |
             docker build -t  8753/docker-react:latest -f Dockerfile.dev .   
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_TOKEN}}         
      - name: Push to dockerhub
        run: docker push  8753/docker-react:latest       
      - name:   Run test
        run: docker run  8753/docker-react:latest npm run test -- --coverage  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
        application_name: frontend
        environment_name: frontend-env
        #version_label: app-9336-240412_152218437394
        region: ${{ secrets.AWS_DEFAULT_REGION }}