name: build and deploy on EBS
on:
  push:
    branches:
      -  master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build docker image
        run: |
             docker build -t nkathad/docker-react -f Dockerfile.dev .
      - name:   Run test
        run: docker run nkathad/docker-react npm run test -- --coverage  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Elastic Beanstalk CLI
        run: |
             pip install awsebcli
    
    
      - name: Deploy to Elastic Beanstalk
        run:  |
              eb init
    
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: frontend-Environment
          region: us-east-1
          deployment_package: nkathad/docker-react
