on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
             docker build -t nkathad/docker-react -f Dockerfile.dev .
             docker push nkathad/docker-react
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Uncomment if you want to run tests
      # - name: Run Tests
      #   run: docker run nkathad/docker-react npm run test -- --coverage
      - name: Set Version Label
        id: version
        run: echo "::set-output name=version_label::$(date +'%Y%m%d%H%M%S')"
        shell: bash

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
          application_name: frontend
          environment_name: frontend-env
          version_label: ${{ needs.build.outputs.version_label }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}